/* Single line comment */
CREATE TABLE cliente (
  cod_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1004 INCREMENT BY 1) NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  tipo_documento VARCHAR(4) NOT NULL,
  nro_documento VARCHAR(20) NOT NULL,
  PRIMARY KEY(cod_cliente)
);


INSERT ALL 
  INTO cliente (cod_cliente, nombre, tipo_documento, nro_documento) VALUES ('1001', 'ABC TRANSPORTES', 'RUC', '20257758214')
  INTO cliente (cod_cliente, nombre, tipo_documento, nro_documento) VALUES ('1002', 'JUAN PEREZ', 'DNI', '57485362') 
  INTO cliente (cod_cliente, nombre, tipo_documento, nro_documento) VALUES ('1003', 'MARIA LOPEZ', 'DNI', '26534857')
  
SELECT 1 FROM DUAL;


